def splash():
    print("\n")
    print("$$\      $$\           $$$$$$$$\ $$\                 $$\ ")
    print("$$$\    $$$ |          $$  _____|\__|                $$ |")
    print("$$$$\  $$$$ | $$$$$$\  $$ |      $$\ $$$$$$$\   $$$$$$$ |")
    print("$$\$$\$$ $$ |$$  __$$\ $$$$$\    $$ |$$  __$$\ $$  __$$ |")
    print("$$ \$$$  $$ |$$ /  $$ |$$  __|   $$ |$$ |  $$ |$$ /  $$ |")
    print("$$ |\$  /$$ |$$ |  $$ |$$ |      $$ |$$ |  $$ |$$ |  $$ |")
    print("$$ | \_/ $$ |$$$$$$$  |$$ |      $$ |$$ |  $$ |\$$$$$$$ |")
    print("\__|     \__|$$  ____/ \__|      \__|\__|  \__| \_______|")
    print("             $$ |                                        ")
    print("             $$ |                                        ")
    print("             \__|                                        ")
    print("v 2.0")
    print("\n")
    print("Created by: boijec")
    print("https://www.github.com/boijec")
    print("\n")

def bad_splash(gate):
    print("mpFind - Media Player Finder")
    print("--------------------------")
    print("Your default gateway is : %s" % gate)
    print("To scan the LAN, take your default gateway, replace the last number with: a \'*\'")
    print("the script accepts input arguments: ")
    print("example: py mpFind.py { your ip-range }")
    print("--------------------------")